### ISSUE TITLE
Keep your code DRY

### ISSUE THREAD

**Issue by zannain** [quixotep/prj-rev-bwfs-dasmoto#2]
**Don't Repeat Yourself**

This is perhaps one of the most well know programming principles and for good reason, when you can write less code and still achieve similar performance this has implications such as better productivity, workflow and code extensibility. You use `*` to give the entire web page a font-family of Helvetica. Nowhere in your styles is there a change in the font and so there is no need to repeat yourself on line [7, 15 and 34](https://github.com/quixotep/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Web%20Design/resources/style.css#L7-L34).

**Comment by quixotep** [comment]
I was wondering about that.
