### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by zannain** [quixotep/prj-rev-bwfs-dasmoto#3]
Make sure to test the responsiveness of your webpage. Chromes' developer tools has great features built into their inspector that allows you to view your webpage in various sizes and see where there may be need to some media queries because the responsiveness of your web page breaks for one reason or other. When I resized your browser I noticed that heading began to disappear.

![image](https://user-images.githubusercontent.com/24375741/35426908-5559499c-0234-11e8-9f28-dd7b4a24d5cd.png)

You can use Chrome Developer Tools to resize your webpage and the tool will tell you what size page your are viewing and you can then use media queries to adjust your styles. You can read more about [media queries here](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)

**Comment by quixotep** [comment]
thanks for explaining that chrome developer tool.  chrome developer is a little overwhelming.  i feel like there is probably a class on that tool all by itself.
